#
# This file is part of Python Client Library for WTSS.
# Copyright (C) 2022 INPE.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.
#

kind: pipeline
name: wtss.py

steps:
- name: build-test
  image: python:3.7
  environment:
    WTSS_EXAMPLE_URL: http://www.esensing.dpi.inpe.br
    WTSS_TEST_URL: http://www.esensing.dpi.inpe.br
  commands:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install -e .[tests,docs]
    - ./run-tests.sh

- name: coverage
  image: plugins/codecov
  settings:
    token:
      from_secret: codecov_token
    files:
      - coverage.xml
      - .coverage
  when:
    event:
      - push

- name: pypi
  image: plugins/pypi
  settings:
    username:
      from_secret: pypi_user
    password:
      from_secret: pypi_pass
    repository: https://upload.pypi.org/legacy/
    distributions:
      - sdist
  when:
    event:
      - tag

- name: discord-notify
  image: brazildatacube/bdc-drone-discord
  settings:
    webhook:
      from_secret: discord_webhook
  when:
    status:
      - failure
      - success