kind: pipeline

name: wtss.py

steps:
    - name: build

      image: python:3.7

      environment:
          WTSS_EXAMPLE_URL: http://www.esensing.dpi.inpe.br
          WTSS_TEST_URL: http://www.esensing.dpi.inpe.br

      commands:
          - pip install --upgrade pip
          - pip install --upgrade setuptools
          - pip install -e .[tests,docs]
          - ./run-tests.sh

    - name: coverage

      image: plugins/codecov

      when:
          event:
              - push
      settings:
          token:
              from_secret: CODECOV_TOKEN

          files:
              - coverage.xml
              - .coverage