kind: pipeline

name: wtss.py

steps:
    - name: build
      image: python:3.7
      environment:
          WTSS_EXAMPLE_URL:
              from_secret: WTSS_EXAMPLE_URL
          WTSS_TEST_URL:
              from_secret: WTSS_TEST_URL
      commands:
          - pip install --upgrade pip
          - pip install --upgrade setuptools
          - pip install -e .[tests,docs]
          - ./run-tests.sh

    - name: coverage
      image: plugins/codecov
      settings:
          token:
              from_secret: CODECOV_TOKEN
          files:
              - coverage.xml
              - .coverage